- components/Head.tsx
- pages/dashboard.tsx
- pages/index.tsx
Previously, our pages had no `<title>` or favicon. This adds some meta data, including the responsive width tag, plus Google Analytics
> [enhancement] added custom Head component for title tags, Google Analytics, favicon, and more

- components/FormStepper.tsx
- components/applicationSteps/ApplicationStep.tsx
- components/applicationSteps/ProfileStep.tsx
- components/applicationSteps/ResultStep.tsx
- components/applicationSteps/StatusStep.tsx
- odyssey.d.ts
- pages/dashboard.tsx
- server.js
Previously, clicking a tab didn't affect the browser history. This would break the back button which users will expect to work. This makes it so tabs can be linked to via a url (`/dashboard/application`) and so that they add on to the browser history, allowing for the back button to be used.
Also made some changes to rendering logic for save + submit buttons and did some small usability stuff. Also set up temporary `results` tab.
TODO: Prevent users from moving onto application or results tab until they've completed the tab prior
> [enhancement] application tabs affect browser history, can be linked, and other usability things

- api/login.js
Fixes #59, so now logging out works
Evidently heroku doesn't let you `GET` the application with the port specified, so this change basically removes the port part for non-local deployments, which then fixes the issue.
> [bugfix] removing port from production deploy 

- components/Hero.tsx
the blob is a PITA to deal w/ for small screens so this PR just hides it
Deals with #64
> [fix] hide blob on mobile, thus improving odyssey's logged-out landing page

- components/steps/Status.tsx
- package.json
- pages/_app.tsx
- pages/dashboard.tsx
- yarn.lock
Right now, it doesn't seem like #63 is happening in staging anymore.. but just in case, this PR changes the status page logic so that it does additional checks to ensure a user sees the right "next steps"
TODO:
* Add Sentry client-side logging
> [fix] status page does additional checks in case status doesn't update properly

- api/login.js
- lib/authenticate.tsx
Moves `/login`, to `/`, so that way at least our app doesn't `404`
> removing login reroutes

- package.json
- server.js
- yarn.lock
This PR enables cookies for sessions. This stores session data in cookies which is stored in the client. Previously, session data was stored on the server in-memory.
This meant that when the server re-booted, session data was lost and users had to log back in. This hurts us for continuous deployment because it means every time we deploy, users will have to log back in. Not ideal if we're pushing out updates constantly 
Reading:
https://expressjs.com/en/advanced/best-practice-security.html
https://github.com/expressjs/cookie-session
https://stackoverflow.com/questions/23566555/whats-difference-with-express-session-and-cookie-session
#106
> [enhancement][server] enable cookie sessions for persistent sessions

- api/admin.js
* Adds endpoint for getting all eligible Reviews 
This fixes the issue of having one person submit an individual review, and is part of a larger rework to fix how exactly the backend infra will look to support app review. Instead of having a single endpoint that manages everything, we can pull all eligible `hackerProfiles`, and then choose from there to `POST` to create a new hacker Profile (endpoint coming soon), to submit a new review. This way we separate the responsibility across multiple endpoints and provides the frontend with more control as to how to create and manage reviews, without having to deal with the filtering business logic.
> [server][app review] Adds `GET` route for all profiles that can currently be reviewed by a person

- api/admin.js
- lib/admin.tsx
- pages/appReview.tsx
* adds an `/api/admin/reviewHistory` route that shows the review history of the logged-in user 
* app review page uses this to show how many user has reviewed
> [fix] add review history route to show reviews logged in user has made

- components/results/Accepted.tsx
Most browsers will show warnings if a field is missing, but because of the way file upload is styled, that warning doesn't show on browsers like Chrome. 
What this PR does is display a specific error message if the travel plan file upload is missing
> [fix] better warning message for when file is missing

- api/hackerProfile.js
- components/results/Declined.tsx
- components/steps/Status.tsx
If a user has the status of `declined`, they'll see these options on their status and results page. If they click the 'Undecline' button, it will set their status to `accepted` and will redirect them to the dashboard
> [enhancement] let users un-decline

- api/database/migrations/20200124192357-augment-contrib-with-multiplier.js
- api/models/contribution.js
Kushell, waking up from his hackerexp duties induced nap, sees a sponsor workshop is happening in 15 minutes. No one has reacted to the post on slack. *Shit*, he says, we need to pump this to the moon. He fires up the **ODSC CMS** (cuz we have one of those), which conveniently supports creating an Api Rush, just for moments like these. He creates a rush for sponsor tasks, with a 10x multiplier. He posts this in slack, and the crowd goes nuts. Everyone is showing up to the sponsor workshop to collect those sweet, sweet rewards. As volunteers scramble to check people in, every contribution getting added to our god log (the contributions table), is signed with a multiplier value, that gets calculated dynamically based on the multipliers table (trust, I got the SQL for this). After pulling …
> [database][battlepass] Adds multiplier element to the contrib, as an entry point for API rush

- package.json
- yarn.lock
* Upgrading to next 9.2 will enable typescript optional coalescing. Optional coalescing was not officially supported in next 9.1
I don't know why it worked in local but not production, but alas, here we are
> [fix] fix dashboard internal error

- lib/api-sdk/fetcher.tsx
the rogue semicolon messed up query params
> [fix] fix bug with urlParams

- .circleci/config.yml
`yarn build` sometimes catches stuff we don't see in `yarn dev` 
this will run `yarn build` to ensure ci catches it so we don't accept a broken build PR
> [ci] add build job to circle CI

- api/admin.js
- api/database/migrations/20200127000435-modify-role-superadmin-volunteer.js
- api/models/hackerProfile.js
- lib/admin.tsx
- odyssey.d.ts
- pages/admin.tsx
- pages/roleManager.tsx
Really simple addition for role-setting capabilities when you're an admin
Someone double check my migration to make sure its good, since I've never done it before. Basically I updated the enums for hackerprofile roles from ['hacker', 'admin', 'sponsor', 'superadmin'] to ['hacker', 'admin', 'sponsor', 'volunteer']. I don't think this changes anything on prod since nobody is superadmin.
This is what it looks like:
> [permissions] add volunteer role & admin role changer

- components/steps/Confirmed.tsx
hackers shouldn't see a QR code before they are checked in. remove that QR code and display a generic message
> [frontend] new confirmed screen, removes QR code

- api/live.js
* Adds endpoint that returns the following Shape: 
```json
{"success":[
{"totalPoints":"26",
"Task": {"id":11,
"points":13,
"description":"",
"blocking":false,
"type":"volunteer",
"isGroupTask":null,
"isActive":true,
"name":"TestTask1",
"createdAt":"2020-01-26T20:31:04.000Z",
"updatedAt":"2020-01-29T03:19:32.000Z",
"groupingId":1}}]}
```
Thought is to hook up the scanner to return this, and return the "totalPoints" value to the volunteer, so we can determine hacker's total points quickly for project dist.
> [server] [feature] Adds serverside support for calculating user Points 

- components/Countdown.tsx
This fixes #364 to show the current year in the countdown banner.
> Update Live page to show current year

- components/Footer.tsx
- components/results/Confirmed.tsx
- components/results/Declined.tsx
- components/steps/Confirmed.tsx
- components/steps/Status.tsx
> fix footer HackSC copyright

- components/steps/Status.tsx
- pages/appform.tsx
Closes #361 
when clicking `fill out my application` on application page, it re-routed to the same page. The previous page was removed when the live website was merged.
> fix missing application page

- api/event.js
- api/public.js
- components/hackerDashboard/widgets/sidebar/events.tsx
Changed public and admin get event routes to sort by ascending
Events widget: updated dates, scroll position starts at next event, old events are grayed out
(screenshot is pre-date-formatting, but example of where the scrollbar would be on page load)
(grayed-out events)
> fixed event routes + edited events widget

- api/database/migrations/20210212031418-add-api-properties.js
- api/models/apis.js
- components/hackerDashboard/Resources.tsx
- components/hackerDashboard/index.ts
- components/hackerDashboard/widgets/index.ts
- components/hackerDashboard/widgets/resources.tsx
- odyssey.d.ts
- pages/resources.jsx
- pages/resources.tsx
Dashboard Resources Page
- const resources = [{title: ..., imageUrl: ..., description: ..., slackChannel: ...}, { ... }, { ... }] array that can be easily replaced with a json object that's returned from the backend
- pngs or images with white backgrounds can be included as image urls 
- if description runs long and cannot fit in the ResourceBlurb div with the button to join the slack channel, blurb is scrollable
- resources widget keeps everything centered, fits as many in a row as possible (see screenshots)
> resources page
