- .circleci/config.yml
* Set up CircleCI config for client
> [WIP/Do Not Merge][Setup] Use CircleCI for continuous integration and deployment

- .circleci/config.yml
- package.json
Should fix issues with CircleCI and enable us to run it properly for `client`
> [Fix] CircleCi config was not working

- .circleci/config.yml
- package.json
- server/.ebignore
- server/.gitignore
- server/package.json
- server/src/routes/api.js
- server/tests/sample.test.js
- server/yarn.lock
* Sets up CircleCI integration w/ Elastic Beanstalk
* Set up tests for `server`
* Added a temporary test route
> [Setup] CircleCI for Elastic Beanstalk, server tests, and sample routes

- client/package.json
- client/pages/index.tsx
- client/pages/login.tsx
- client/yarn.lock
- server/package.json
- server/src/app.js
- server/src/migrations/20191010225527-create-hacker-profile.js
- server/src/models/hackerProfile.js
- server/src/models/index.js
- server/src/models/user.js
- server/src/routes/api/hackerProfile.js
- server/src/routes/api/index.js
- server/src/routes/api/testRoutes.js
- server/src/routes/api/users.js
- server/src/routes/index.js
- server/src/server.js
- server/src/utils/server.js
- server/tests/sample.test.js
- server/yarn.lock
This change adds a couple of things, including signin, logout, and how to use the auth0 authentication to get a token and send it to the server. 
Running manually for now
It seems like auth0 has some weird cookie explosions that causes weird issues in dev when you hot reload the page a bunch of times. I'm not sure if this is something that we will encounter running in prod, but for context, here: https://github.com/auth0/auth0-spa-js/issues/217. Will investigate further, but for now this should give us a path towards starting application development
> [client][authentication 2/x] Adds login button, conditional rendering on login state, and also a sample approach to making authenticated requests

- client/components/HeaderComponent.tsx
- client/lib/authenticate.tsx
- client/pages/api/login.js
- client/pages/dashboard.tsx
- client/pages/index.tsx
- client/pages/login.tsx
* Adds `/auth/profile` endpoint to get user session data on client 
* Uses above endpoint to handle state discrepancy when doing serverside prop hydration vs. clientside prop hydration. 
Unfortunately just going through manual testing for the moment
> [fullstack][auth 4/x] Now handles clientside/serverside render discrepancy

- client/api/hackerProfile.js
- client/api/models/hackerProfile.js
- client/migrations/20191010225527-create-hacker-profile.js
- client/pages/dashboard.tsx
* `PUT` endpoint for hacker profiles now works
* Schema updated so that our DRY source of truth for identity is auth0, and hacker profiles are tied to that identity (RIP `user` table)
Continues to be manual, no time to setup webdriver tests :(
> [server][2/x] Now has endpoint for updating hacker profiles

- .babelrc
- package.json
- pages/_app.tsx
- pages/_document.tsx
- pages/sample.tsx
- styles/Button.tsx
- styles/GlobalStyles.tsx
- styles/Theme.tsx
- styles/index.tsx
- theme.d.ts
- yarn.lock
latest changes broke styling w/ server side rendering -- this PR fixes that and does some additional configuration
also introduces a theme accessible to all styled-components via a top level `ThemeProvider` -- win for consistent styling
> [client] additional front-end configuration and theming

- .babelrc
- .sequelizerc
- migrations/20191028071621-update-hackerProfile.js
- package.json
- yarn.lock
*Now has application info in accordance with [this](https://quip.com/7srEApv32jfP)
* Sets up some sequelize config stuff so we can do things like es6
> [server][database] Adds HackerProfile include application info

- .babelrc
- migrations/20191028071621-update-hackerProfile.js
- server.js
* We can now actually build the whole project without it giving a `500`
* Migrations now work better
> [bugfix][server] fixes build time config that was causing compilation failures, as well as a couple minor migration fixes

- api/admin.js
- api/hackerProfile.js
- api/user.js
- api/utils.js
- server.js
* hackerProfile routes now prevent writing things like role and status, so people can't game the system
*  adds admin route for updating hackerProfiles
* Tested manually
> [admin][server] adds admin routes and better protects hackerProfile routes

- api/database/migrations/20191101021240-mlh-app-requirements.js
- api/hackerProfile.js
- api/models/hackerProfile.js
- components/Select.tsx
- components/applicationSteps/ApplicationStep.tsx
- components/applicationSteps/ProfileStep.tsx
- components/applicationSteps/ResultStep.tsx
- lib/formSubmission.tsx
- odyssey.d.ts
- pages/dashboard.tsx
- styles/Form.tsx
Built out the UI for the application step of the process. Added a `/api/profile/application` route that specifically handles the logic for this step
TODO: better input validation and error handling
> [client][api] build out application form and support saving and submission

- components/Hero.tsx
- package.json
- yarn.lock
> [client] logged out home page

- components/Blob.tsx
- components/Hero.tsx
- components/Navbar.tsx
- components/applicationSteps/ApplicationStep.tsx
- components/applicationSteps/ProfileStep.tsx
- components/applicationSteps/StatusStep.tsx
- styles/Column.tsx
- styles/Flex.tsx
Currently, Odyssey will render certain parts of the dashboard strangely. This modifies some of the existing styles so that Odyssey plays nicer on mobile browsers
> [enhancement] UI renders properly on mobile devices

- components/applicationSteps/StatusStep.tsx
- lib/authenticate.tsx
* Small bugfix that allows new users to get started
* Changes fetch url based on whether we're on the client or the server.
> [deployment] Small bugfix that prevented new users from starting the flow, and fixes fetch issues

- api/hackerProfile.js
- components/applicationSteps/ProfileStep.tsx
- components/applicationSteps/StatusStep.tsx
- lib/authenticate.tsx
- lib/formSubmission.tsx
- package.json
- server.js
- yarn.lock
Ignore previous PR for resume uploading, was too lazy to fix merge since it isn't that much code so the relevant changes are just in this PR
> [fullstack] Take 2 at wiring resume uploading, without deleting a bunch of code

- lib/getProfileStage.tsx
The change is one line, mega minor but now the build doesn't break
> [bugfix] fixes wording issue that causes build failure

- api/hackerProfile.js
#65 Is hard to repro, but hopefully this should fix it. Will be monitoring sentry signal to see if this problem continues to show up after this change but tentatively I think it should help.
> [bugfix] Should fix default value failures on signin

- api/hackerProfile.js
- api/models/hackerProfile.js
This should fix errors related to: https://sentry.io/organizations/hacksc-p6/issues/1314898028/?project=1801129&query=is%3Aunresolved 
Should deal with #56
> [fix] sets userId as a primary key which should fix timeout issues

- api/hackerProfile.js
- components/steps/Profile.tsx
- lib/formSubmission.tsx
Life is too short for descriptions, resume location mutation happens on the server now. 
Also hopefully fixes #71
> [server][bugfix] Moves resume location to the server

- components/steps/Profile.tsx
- package-lock.json
> [fix] selecting a file for resume upload changes the label

- components/steps/Status.tsx
> [enhancement][feat] add countdown to dashboard status step

- api/database/migrations/20191111203354-add-promo-codes.js
- api/hackerProfile.js
- api/models/hackerProfile.js
- components/steps/Profile.tsx
- components/steps/Status.tsx
- lib/formSubmission.tsx
- odyssey.d.ts
Basic implementation
Closes #98
> [feat] adds referral codes

- components/Head.tsx
I've done it! @saresend will have work for many a year to come
Closes #102
> Adds Facebook tracking pixel

- components/steps/Status.tsx
- styles/Button.tsx
Adds a button add to gcal under days left
> [enhancement] Adds a add to gcal button to days left

- api/admin.js
- api/database/migrations/20191115010855-add-review-table.js
This adds the hacker Review table so that we have a database table from which to work off of
Begins work for #95
> [database][admin 1/x] Adds HackerReviews table 

- api/hackerProfile.js
- api/models/hackerProfile.js
- components/steps/Status.tsx
- lib/layouts.tsx
- odyssey.d.ts
- package.json
- yarn.lock
Does as it says.
The lack of referral codes as a seperate table makes this kinda stupid implementation wise, basically do a manual join after the instance is found, because sequelize doesn't support async getters.
> [feat][enhancement] adds a board of who you have referred

- components/Navbar.tsx
- lib/authenticate.tsx
- pages/admin.tsx
- pages/dashboard.tsx
* Adds minimal admin page as baseline for admin  to do stuff
* Adds routing logic based on a user's role
> [WIP][fullstack][admin 3/x] Adds rerouting logic so admins get redirected to admin portal

- api/database/migrations/20191114212136-teams.js
- api/models/hackerProfile.js
- api/models/team.js
- api/team.js
- odyssey.d.ts
- server.js
DB work for teams feature. #132
> [feat][backend][1/x] sets up team table and links hacker profile model to teams

- api/database/migrations/20191114212136-teams.js
- api/models/hackerProfile.js
- api/models/team.js
- api/team.js
- odyssey.d.ts
- server.js
This was previously reverted but now that future migrations are fixed, this should be good to go once again
> [try #2][backend] sets up db migrations + schema for teams tables

- api/database/migrations/20191114212136-teams.js
- api/database/migrations/20191126000713-teams-add-dates.js
- api/hackerProfile.js
- api/models/hackerProfile.js
- api/models/team.js
- api/team.js
- components/CreateTeamForm.tsx
- components/JoinTeamForm.tsx
- components/Team.tsx
- odyssey.d.ts
- pages/teams.tsx
see title, builds on top of #139 
testing these routes is a pain in the ass, ready for these to be reviewed but won't merge until serious further testing is done 
UPDATE: ended up building some interfaces to test API routes
> [feat][backend][2/x] sets up API routes for creating/joining/leaving team

- pages/teams.tsx
seeing build errors from heroku. related to typescript. this fixes.
> [hotfix] fixes build error related to typescript

- api/database/migrations/20191126043728-create-task-table.js
- api/models/task.js
- api/tasks.js
- server.js
* Adds Task model
* Adds Task migration 
* Basic `GET` route to find all existing tasks
This begins to handle #149, so we can start creating tasks that have point assignments
> [server][points 1/x] Adds tasks models, migrations, and basic GET route

- components/steps/Profile.tsx
- components/steps/Status.tsx
- lib/formSubmission.tsx
> [fix] remove referrer code

- pages/testconsole.tsx
* Go to `URL_BASE/testconsole` when working on dev to get a really budget postman that does in fact do the session handling for you. Good for quick and dirty endpoint testing, mostly
> [QoL] [Frontend] Adds the postman that mom has at home, for testing auth'd endpoint routes

- api/admin.js
* Adds endpoint so we can actually query what reviews we've already made
> [server][review portal] Adds an "all reviews" endpoint so we can actually go back and edit previous reviews

- api/admin.js
* See title 
This is added so that the frontend can have more control over when reviews are being created, and separate the responsibility of querying for profile and creating reviews
> [server][app review] Adds post endpoint for creating new reviews

- pages/admin.tsx
- pages/appReview.tsx
**Admin Dashboard**
**App Review**
Still working on this but this sets up some clean UI for the admin + app review pages
**TODO**
> [admin][ui] new designs for admin and app review pages

- lib/admin.tsx
- pages/appReview.tsx
> [enhancement] added info panel w/ link to rubric and a count of how many profiles user has reviewed

- pages/appReview.tsx
Server side rendering is expensive -- to cut down on CPU usage, instead of reloading the page (which was a dirty hack), we re-fetch the profile
Had to introduce more states and yadadadada but oh wellz, this is better than before
> [fix] fetch new profile on submit instead of reloading page

- pages/appReview.tsx
> [hotfix] show loading text when retrieving new profile

- lib/admin.tsx
See my Slack messages in #2020-engineeling-closed for an explanation
> [fix] randomly select eligible review

- api/admin.js
> [server][app review] Reduces required reviews to two

- cronjobs/sendgridsync.js
- package.json
- server.js
- yarn.lock
Sets up a cron job to sync hacker profiles to sendgrid this way we shouldn't have to deal with marketing requests for emails ever again.
> Sendgrid contact sync cron job

- api/database/migrations/20191226014741-confirmed-at-field.js
- api/hackerProfile.js
- api/models/hackerProfile.js
> [hotfix] add confirmedAt and declinedAt date fields

- components/results/Rejected.tsx
- components/steps/Results.tsx
- components/steps/Status.tsx
**Dashboard Message**
**Results Tab**
> [enhancement] add rejection message

- api/database/migrations/20200115235853-add-travel-column.js
- api/models/hackerProfile.js
Addresses #202 
One question though: how exactly do you want this populated?
> [database] Adds travel reimbursement status column

- api/database/migrations/20200118201352-add-task-type.js
- api/models/task.js
- api/people.js
- api/tasks.js
- lib/live.tsx
- pages/admin.tsx
- pages/taskManager.tsx
I'm doing frontend stuff. It looks like shit, I apologize lol
* Provides an interface for creating and deleting tasks
> [WIP][admin][battlepass] Adds task manager dashboard so we can set up tasks

- api/database/migrations/20200120005508-create-prize.js
- api/database/migrations/20200120005653-create-projectTeam.js
- api/database/migrations/20200120005958-associate-projectTeams-prizes.js
- api/database/migrations/20200120011322-associate-projectTeams-persons.js
- api/models/person.js
- api/models/prize.js
- api/models/projectTeam.js
- package.json
- yarn.lock
Adds the requisite functionality for a teams dashboard
**Important Notes**
ProjectTeams is for during the Hackathon | Teams is for applications
> [Server][Battlepass] Sets up tables and migrations

- api/login.js
Put this up to help with API dev, use it to create a session without going through Auth0 | bless up. Enables the use of postman
> Creates dev bypass

- api/live.js
- api/models/person.js
* Adds an endpoint that dumps a small *shitload* of data about houses
https://pastebin.com/xxH9TA9t - link for example output
> [server][battlepass] Adds an endpoint to support house view in dashboard

- api/live.js
> [Server][Battlepass] Adds house info queryable by specific ID 

- package.json
- yarn.lock
one of the easiest ways to improve performance 
see: https://twitter.com/mxstbr/status/1216791579345727493
> [update] update styled-components to v5

- package.json
- pages/_app.tsx
- yarn.lock
Uses React Toast Notifications
please replace all future notification messages with this
> Adds Toasts

- api/live.js
Closes #238, and adds a way to add contributions by email (best effort basis here, since the association isn't guaranteed)
> [Server][Battlepass] Adds email contrib handler

- api/database/migrations/20200126213315-adds-timestamps-to-prizes.js
- api/models/prize.js
- api/models/projectTeam.js
- api/prizes.js
- components/ButtonWithTextForm.tsx
- express.js
- odyssey.d.ts
- pages/_app.tsx
- pages/projectTeam.tsx
- tests/api/prize.test.js
It's only a partial but want to merge now
- Adds route for prizes
- ProjectTeam Page (Creation not rendering)
- Changes ProjectTeam default scope to include all associations
> [FullStack] Create teams pages

- api/database/migrations/20200127012812-add-qrcode-to-hacker-profile.js
- api/live.js
- api/models/hackerProfile.js
Quick API route that lets hackers search hackers up by a first name, last name, and/or e-mail 
Will likely expand this a bit further later, but for now this will do
> [2/x][backend] Hacker lookup API route

- api/live.js
- pages/admin.tsx
- pages/checkin.tsx
**How This Works**
Volunteers get access to this interface that lets them look up hackers by first name, last name, and/or e-mail.
Once they have manually verified a hacker is who they say they are, and they are eligible to check in, the volunteer will hand the hacker a QR code name tag that has a 4 letter code on it (ex: DYEX)
The volunteer will input this in the interface, assign it to the hacker, then give the physical QR code for the hacker to get scanned in by another volunteer after they have written in their name
**Goal**
- Minimize number of name tags that are printed
- Enable random assignment of physical QR tags
- Link random physical QR tags to data in Odyssey
> [4/x][fullstack] allow volunteers to look up and assign QR codes to hackers

- api/database/migrations/20200127012812-add-qrcode-to-hacker-profile.js
- api/live.js
- api/models/hackerProfile.js
Wrote route to be used by volunteers to assign QR codes to users
> [WIP][3/x][backend] Wrote POST route to assign QR codes to hacker profiles

- api/live.js
- components/Scanner.tsx
- pages/_app.tsx
- pages/admin.tsx
- pages/scan.tsx
Kill the jank thing I was doing to show feedback, instead use `react-toast-notifications` 
Thank you, abstractions!
> [enhancement] use react-toast-notifications for qr code scanning

- api/live.js
Closes #269, now will 400 in the case of duplicate tasks
> [server][bugfix] 

- api/prizes.js
- api/projectTeam.js
- lib/api-sdk/fetcher.tsx
- lib/api-sdk/projectTeamHooks.tsx
- odyssey.d.ts
- package.json
- pages/projectTeam.tsx
- tests/api/prize.test.js
- tests/api/projectTeam.test.js
- yarn.lock
- Creates a data client and ports ProjectTeam page to it
- See API Interface Quip document for design notes
- Please review design not just code semantics
> [4/x] Initial Client Design

- pages/scan.tsx
> [hotfix] fix another prod bug

- api/hackerLive.js
* Worst case backup that sets up the final battlepass structure. Will change to be SQL after, but this way we can at least get it displayed on prod.
> [caveman change][battlepass] Hardcodes the structure of the battlepass (for now)

- api/models/contribution.js
* Assoc'd task data should now get through in the personInfo request
> [server][bugfix] Scopes now properly find Tasks, so they're not null

- api/projectTeam.js
- components/Navbar.tsx
- lib/api-sdk/fetcher.tsx
- lib/api-sdk/projectTeamHooks.tsx
- pages/dashboard.tsx
- pages/projectTeam.tsx
Basically building off of Jack's hard work to make Team management possible in the live dashboard. The whole prize selection business will probably happen sat0rday!
**Disclaimer:** It's me building frontend again so its probs trash
> [frontend][ProjectTeam] Adds support for adding members by QR Id, and adds Team Management Tab

- api/hackerLive.js
- pages/projectTeam.tsx
* Moves the travel reimbursement to the first premium slot so we don't have A N G E R Y hackers
* UI Fixes surrounding project teams and their management
> [Frontend] Cleans up the UI around competing for prizes 

- components/ContributionHistory.tsx
Previously showed an awkward blank screen. Now shows message if no task history
> [frontend] show a message if a user has no task history

- api/admin.js
- api/tasks.js
- api/utils.js
- pages/scan.tsx
> [improvement] pass down roles in auth middleware instead of adding to req

- api/live.js
- pages/checkin.tsx
> [change] show qr input fields for non-confirmed hackers

- components/IncompleteTasks.tsx
- components/steps/CheckedIn.tsx
- lib/api-sdk/fetcher.tsx
- lib/api-sdk/hackerLiveHooks.tsx
> [frontend] show incomplete tasks on odyssey

- components/steps/CheckedIn.tsx
> [temp] replace schedule with link to quip

- components/HouseProgress.tsx
> progress bar patch

- components/events/Event.tsx
- components/events/Events.tsx
- components/steps/CheckedIn.tsx
> [frontend] attempt at an alternative schedule

- pages/judgingManager.tsx
> [judging] removed email from table assignments

- pages/judgingManager.tsx
> [judging] extra display info

- api/hackerLive.js
- api/live.js
Endpoint should be at `/api/hacker/live/rafflePoints`, response looks like:
```
{"success":{"totalRafflePoints":10}}
```
Assuming we're gonna have the setup for setting isBattlepassComplete on the persons table to true, this should now accurately compute raffle tickets. @jzeiders, we'll figure out how to do it in pure SQL once I'm less under such a time crunch
> [server][enhance] Adds 6k tiers instead of 8k, adds submit action handler, and also a totalRafflePoints endpoint

- components/BattlePass.tsx
- components/RaffleTicketCount.tsx
- components/events/Event.tsx
- components/steps/CheckedIn.tsx
- lib/api-sdk/fetcher.tsx
- lib/api-sdk/hackerLiveHooks.tsx
> [frontend] raffle ticket count

- pages/scan.tsx
This PR makes the point total action more generic since we have more prizes than just t-shirts
> [frontend] change point total action to just spit out point total 

- pages/projectTeam.tsx
Prizes can't go down if we don't have them
> Project prizes are for losers

- api/live.js
- pages/scan.tsx
New action will be called "confirm project submission", and we'll have volunteers scan everyone who's tabling. It's linked up to projectTeams so you'd only need to scan one person on the team. Works for solo-hackers too, it'll just ignore projectTeams profile and enable battlepass for them.
> [scan] judge action

- pages/judgingManager.tsx
> [judging] parse video link

- api/hackerLive.js
- scripts/ticketRaffle.js
temporarily withhold giving tickets to winning house
> [update] temporarily withhold giving tickets to winning house

- pages/admin.tsx
Render date properly in channel name in the dashboard description below.
> dynamically render date

- api/team.js
- components/Team.tsx
Finally added the functionality that allows team owner to kick members of their team.
Closes #142
> Allow team owners to kick other members

- .kodiak.toml
PR's with the `automerge` label will be automerged if approved and tests are passing
> Setup Kodiak

- components/Modal.tsx
- components/steps/Status.tsx
- package.json
- pages/admin/hackerManager.tsx
- pages/admin/testconsole.tsx
- yarn.lock
Modal will be needed later, but also wanted a way to view profiles now.
> Add basic modal component and allow viewing hackers full profile in Manage Hacker page

- api/admin.js
- lib/admin.ts
- pages/admin/checkin.tsx
- pages/api/admin.ts
Batch Check-In textarea
- Displays error & success messages
- Checks in all valid entries
- Leaves all invalid entries in the textarea
- Automatically capitalizes qrcode
Also added small stats panel (only updates on refresh - getInitialProps) of # checked in, accepted, waitlisted, and rejected
> Hacker CheckIn

- api/database/migrations/20210110021415-hackathon-constants-add-type.js
- api/hackathonConstants.js
- api/models/hackathonConstants.js
- lib/hackathonConstants.ts
- odyssey.d.ts
- pages/admin/hackathonConstantsManager.tsx
Added migration / edited model / edited routes / updated hackerConstantsManager
It's failing E2E tho and I'm not sure why. Is the migration run on the db before the test suite?
> Hacker Constants

- components/hackerDashboard/AdminDashboard.tsx
- components/hackerDashboard/Application.tsx
- components/hackerDashboard/Dashboard.tsx
- components/hackerDashboard/index.ts
- components/hackerDashboard/layout/Header.tsx
- components/hackerDashboard/layout/Navbar.tsx
- components/hackerDashboard/layout/index.ts
- components/hackerDashboard/widgets/admin/index.ts
- components/hackerDashboard/widgets/index.ts
- components/hackerDashboard/widgets/sidebar/events.tsx
- components/hackerDashboard/widgets/updates.tsx
- pages/dashboard.tsx
- fix schedule to be scrollable with max height of 400px
- fix logo to be correct size
- parse left tabs with hackathon Constants
- add module exports to redesigned dashboard components
> add hackathon constants filtering, logo fix, schedule scroll

- components/hackerDashboard/layout/Sidebar.tsx
- components/hackerDashboard/widgets/sidebar/countdown.tsx
- components/hackerDashboard/widgets/sidebar/events.tsx
- lib/hackathonConstants.ts
- package.json
- yarn.lock
Use moment-timezone to account for people joining globally
> Switch hackathon timer to countdown when hacking ends when hackathon starts

- components/hackerDashboard/SponsorDashboard.tsx
- components/hackerDashboard/index.ts
- components/hackerDashboard/layout/Sidebar.tsx
- components/hackerDashboard/layout/SponsorNavbar.tsx
- components/hackerDashboard/widgets/admin/sponsor.tsx
- pages/dashboard.tsx
> Sponsor Dashboard

- api/linkSlack.js
- api/models/hackerProfile.js
- api/models/linkedSlack.js
- api/submitProject.js
- express.js
new branch to fix all the messed up stuff
> Add check in slack command

- pages/dashboard.tsx
depending on user role, should be shown different page on new dashboard
removed switch role button
> manage hacker/admin/sponsor dashboard view

- components/hackerDashboard/widgets/sidebar/events.tsx
So we're pretending that the LA datetimes in the database are "UTC"
Just changed currentDate to be the current UTC date minus 8 hours
> Fixing Dates

- pages/admin/tickets.tsx
> tickets styles

- components/hackerDashboard/Dashboard.tsx
- components/hackerDashboard/widgets/updates.tsx
> Dashboard Problem
